// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WhiteLagoon.Infranstructure.Data;

#nullable disable

namespace WhiteLagoon.Infranstructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250522163704_seedVillaToDb")]
    partial class seedVillaToDb
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WhiteLagoon.Domain.Entities.Villa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("Created_Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Occupancy")
                        .HasColumnType("int");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<int>("Sqft")
                        .HasColumnType("int");

                    b.Property<DateTime?>("Updated_Date")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Villas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Created_Date = new DateTime(2025, 5, 22, 18, 37, 3, 495, DateTimeKind.Local).AddTicks(5017),
                            Description = "This is a description of Royal Villa",
                            ImageUrl = "https://example.com/royal-villa.jpg",
                            Name = "Royal Villa",
                            Occupancy = 2,
                            Price = 200.0,
                            Sqft = 500,
                            Updated_Date = new DateTime(2025, 5, 22, 18, 37, 3, 499, DateTimeKind.Local).AddTicks(618)
                        },
                        new
                        {
                            Id = 2,
                            Created_Date = new DateTime(2025, 5, 22, 18, 37, 3, 499, DateTimeKind.Local).AddTicks(846),
                            Description = "This is a description of Luxury Villa",
                            ImageUrl = "https://example.com/luxury-villa.jpg",
                            Name = "Luxury Villa",
                            Occupancy = 4,
                            Price = 300.0,
                            Sqft = 700,
                            Updated_Date = new DateTime(2025, 5, 22, 18, 37, 3, 499, DateTimeKind.Local).AddTicks(847)
                        },
                        new
                        {
                            Id = 3,
                            Created_Date = new DateTime(2025, 5, 22, 18, 37, 3, 499, DateTimeKind.Local).AddTicks(849),
                            Description = "This is a description of Beachfront Villa",
                            ImageUrl = "https://example.com/beachfront-villa.jpg",
                            Name = "Beachfront Villa",
                            Occupancy = 6,
                            Price = 400.0,
                            Sqft = 900,
                            Updated_Date = new DateTime(2025, 5, 22, 18, 37, 3, 499, DateTimeKind.Local).AddTicks(850)
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
